# config_g68.py - VERSIÓN INTEGRAL FINAL BLINDADA
DICCIONARIO_PESOS = {
    # --- NIVEL CRÍTICO: VETOS Y RIESGO REPUTACIONAL ---
    "estafa": -1.0, "robo": -1.0, "engaño": -0.9, "fraude": -1.0,
    "peligro": -0.9, "asco": -0.8, "chinches": -1.0, "cucaracha": -0.9,
    "sangre": -0.9, "moho": -0.8, "veneno": -0.8, "terror": -1.0, "horror": -1.0,
    "maltrato": -0.9, "inundacion": -0.9, "ignoro": -0.9, "desprecio": -0.8,
    "poco honesto": -0.9, "nada honesto": -1.0, "engañoso": -0.8, "grosero": -0.9,
    
    # --- NEGATIVOS UNIVERSALES Y DE SERVICIO ---
    "pésimo": -0.8, "horrible": -0.8, "malo": -0.5, "lento": -0.5,
    "caro": -0.6, "decepción": -0.7, "nunca": -0.4, "jamás": -0.4,
    "error": -0.6, "problema": -0.5, "espera": -0.4, "suciedad": -0.7,
    "caos": -0.8, "fallo": -0.7, "mediocre": -0.8, "carisimo": -0.8,
    "sucio": -0.8, "mancha": -0.7, "ruido": -0.6, "frio": -0.5,
    "olor": -0.6, "humedad": -0.7, "viejo": -0.6, "pobre": -0.7,
    "invasivo": -0.7, "burocrático": -0.6, "robot": -0.5, "bajado": -0.4,
    "confuso": -0.5, "golpeada": -0.5, "perder": -0.5, "roto": -0.7, "abierto": -0.5,
    "complejo": -0.4, "inferior": -0.5, "imposible": -0.6, "cancelaron": -0.7,
    "spam": -0.6, "rudo": -0.5, "irritante": -0.6, "contradicción": -0.5,
    "pequeño": -0.3, "rayón": -0.5, "frustrante": -0.7, "aburrido": -0.5,
    "tarda": -0.4, "tardó": -0.4, "actualiza": 0.2, "real": 0.1, "prometido": 0.2,
    "valor": 0.4, "valores": 0.4, "familiar": 0.5, "imagen": 0.3, "marca": 0.2,
    "logo": 0.2, "confianza": 0.5, "pisapapeles": -0.8, "basura": -0.9,
    "inútil": -0.8, "insulto": -0.8, "laberinto": -0.6, "mediocridad": -0.7,
    "incompetencia": -0.8, "incompetente": -0.8, "mediocre": -0.7,
    "degradación": -0.6, "decepcionante": -0.7, "caro": -0.6, "pesado": -0.4,
    "pesadilla": -0.8, "rompen": -0.6, "individual": -0.3, "ocultos": -0.5,
    "joder": -0.9, "mierda": -0.9, "estafa": -1.0, "carajo": -0.8,
    "puta": -0.9, "maldita": -0.8, "competencia": -0.5, "diablo": -0.7,
    "falla": -0.6, "no es": -0.3, "no hay": -0.3, "eterno": -0.5,
    "insoportable": -0.7, "guion": -0.4, "mediocre": -0.6, "basura": -0.9,
    "peso": -0.1, # Casi neutro para evitar errores en modismos
    
    # --- POSITIVOS DE ÉLITE (AJUSTADOS PARA SARCASMO) ---
    "excelente": 0.8, "recomendado": 0.8, "bueno": 0.5, "rápido": 0.6,
    "perfecto": 0.7, "genial": 0.4, "increíble": 0.4, "brillante": 0.4,
    "amable": 0.6, "mejor": 0.5, "éxito": 0.7, "maravilla": 0.9,
    "exquisito": 0.9, "impecable": 0.9, "soberbio": 0.8, "lujo": 0.8,
    "sostenibilidad": 0.7, "sostenible": 0.6, "identificado": 0.6,
    "fidelidad": 0.7, "fiel": 0.6, "agradezco": 0.8, "rapidez": 0.8,
    "encanta": 0.5, "resuelto": 0.7, "solución": 0.7, "expectativas": 0.6,
    "superó": 0.7, "identifico": 0.6, "honesto": 0.6, "familiar": 0.5,
    "descuento": 0.5, "renovar": 0.5, "paciente": 0.7, "moderna": 0.5,
    "confianza": 0.7, "ecológico": 0.6, "valoro": 0.5, "compensación": 0.6,
    "asesoría": 0.6, "fluido": 0.6, "inspiradora": 0.7, "limpio": 0.6,
    "proactivo": 0.7, "tendencia": 0.4, "sonrisa": 0.6, "visual": 0.4, 
    "alivio": 0.8, "gracias": 0.5, "resolvieron": 0.8,
    
    # --- PROTECCIÓN DE N-GRAMAS (Prioridad Máxima) ---
    "lo esperado": 0.1, "lo que esperaba": 0.2, "antes de lo esperado": 0.3,
    "tiempo real": 0.5, "sin problemas": 0.8, "nada que ver": -0.6,
    "no se vivir sin": 0.9, "no puedo vivir sin": 0.9, "no vivir sin": 0.8,
    "no haya sido mala": -0.5, "mejor la competencia": -0.7, "atencion de mierda": -1.0,
    "no es": -0.3, "no hay": -0.3, "no funciona": -0.7,
    "quitar un peso": 0.9, "un peso menos": 0.8, "al mejor": 0.6, "valio la pena": 0.8,
    "de un departamento a otro": -0.6, "hablando con la pared": -0.7,
    "sin soluci": -0.6, "no respond": -0.5
}

KEYWORDS_DEPT = {
    "Marketing": {
        "estafa": "Reputación/Fraude",
        "robo": "Reputación/Seguridad",
        "fraude": "Reputación/Legal",
        "peligro": "Seguridad/Marca",
        "caro": "Precios/Percepción",
        "carisimo": "Precios/Crítico",
        "pago": "Precios/Procesos",
        "cobro": "Precios/Procesos",
        "lujo": "Marca/Posicionamiento",
        "sostenibilidad": "Marca/Sostenibilidad",
        "sostenible": "Marca/Sostenibilidad",
        "identificado": "Marca/Identidad",
        "identifico": "Marca/Identidad",
        "fidelidad": "Marca/Lealtad",
        "fiel": "Marca/Lealtad",
        "anuncio": "Campaña/Publicidad",
        "campaña": "Campaña/Promoción",
        "oferta": "Campaña/Promoción",
        "descuento": "Campaña/Promoción",
        "promoción": "Campaña/Promoción",
        "logo": "Imagen/Identidad",
        "moderna": "Imagen/Actualidad",
        "engaño": "Reputación/Ética",
        "engañoso": "Reputación/Ética",
        "imagen": "Marca/Visual",
        "branding": "Marca/Posicionamiento",
        "marca": "Marca/Identidad",
        "nostalgia": "Campaña/Emoción",
        "influencer": "Campaña/Social",
        "eslogan": "Campaña/Mensaje"
    },
    "Operaciones": {
        "lento": "Tiempos/Espera",
        "tarda": "Tiempos/Espera",
        "tardó": "Tiempos/Espera",
        "espera": "Tiempos/Espera",
        "demora": "Logística/Retraso",
        "envío": "Logística/Entrega",
        "entrega": "Logística/Entrega",
        "paquete": "Logística/Producto",
        "reparto": "Logística/Entrega",
        "llegó": "Logística/Estado",
        "recibido": "Logística/Estado",
        "seguimiento": "Logística/Visibilidad",
        "rastrear": "Logística/Visibilidad",
        "suciedad": "Higiene/Estado",
        "sucio": "Higiene/Estado",
        "mancha": "Higiene/Estado",
        "limpio": "Higiene/Estado",
        "ruido": "Infraestructura/Confort",
        "frio": "Infraestructura/Confort",
        "humedad": "Infraestructura/Confort",
        "viejo": "Infraestructura/Mantenimiento",
        "roto": "Producto/Estado",
        "rompió": "Producto/Estado",
        "falla": "Producto/Fallo",
        "fallo": "Producto/Fallo",
        "errores": "Producto/Fallo",
        "actualización": "Producto/Software",
        "batería": "Producto/Hardware",
        "sensor": "Producto/Hardware",
        "wifi": "Producto/Conectividad",
        "instrucciones": "Producto/Manual"
    },
    "Atención al Cliente": {
        "amable": "Trato/Personal",
        "grosero": "Trato/Inaceptable",
        "atención": "Servicio/Calidad",
        "soporte": "Servicio/Calidad",
        "ayuda": "Servicio/Calidad",
        "agradezco": "Satisfacción/Gratitud",
        "alivio": "Satisfacción/Resolución",
        "gracias": "Satisfacción/Gratitud",
        "resolvieron": "Satisfacción/Resolución",
        "rapidez": "Satisfacción/Velocidad",
        "resuelto": "Satisfacción/Resolución",
        "prometido": "Satisfacción/Expectativas",
        "superó": "Satisfacción/Excelencia",
        "robot": "Servicio/Calidad",
        "burocrático": "Servicio/Procesos",
        "paciente": "Trato/Excelencia",
        "grosero": "Trato/Inaceptable",
        "compensación": "Servicio/Recuperación",
        "empatía": "Trato/Humano",
        "sonrisa": "Trato/Hospitalidad",
        "incompetencia": "Trato/Deficiente",
        "incompetente": "Trato/Deficiente",
        "inútil": "Servicio/Calidad",
        "pesadilla": "Trato/Inaceptable",
        "mierda": "Trato/Inaceptable",
        "puta": "Trato/Inaceptable",
        "carajo": "Trato/Inaceptable",
        "guion": "Trato/Robotizado",
        "insoportable": "Servicio/Experiencia"
    },
    "Administración y Procesos": {
        "facturación": "Procesos/Facturación",
        "reembolso": "Procesos/Finanzas",
        "impuestos": "Procesos/Legal",
        "baja": "Procesos/Retención",
        "contrato": "Procesos/Legal",
        "privacidad": "Procesos/Seguridad",
        "nómina": "Procesos/RRHH",
        "pago": "Procesos/Finanzas",
        "auditoría": "Procesos/Control",
        "laberinto": "Procesos/Complejos",
        "burocracia": "Procesos/Lentos",
        "ocultos": "Procesos/Transparencia",
        "estafa": "Seguridad/Fraude",
        "eterno": "Procesos/Velocidad"
    }
}