spring.application.name=api


#Port API
server.port=8000

#Port ML
ml.base-url=http://localhost:8080
ml.predict-path=/predict/sentiment
ml.timeout-ms=15000

# H2 Database Console (solo laboratorio local)
# H2 Database Console (solo laboratorio local)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/sentiment_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=contrasenia

# PostgreSQL Configuration (Docker) - PLAN FUTURO
# spring.datasource.url=jdbc:postgresql://localhost:5432/sentiment_db
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
